[features]
seeds = false
skip-lint = false
[programs.localnet]
gifportal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anoy/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run mocha -t 1000000 tests/"
