[features]
seeds = false
skip-lint = false
[programs.devnet]
gifportal = "9W4Rag5f4e4qWbNazMTmWthGvkXjJjdK734QejMd2m42"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anoy/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
